name: project-workflow
on: [push]
jobs:
  project-one-job:
  runs-on:  ubuntu-latest
  steps:
    - name: checkout projectone source code
      uses: actions/checkout@v3
    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'  
    - run: npm install
    