name: project-workflows
on: [push]
jobs:
  project-one-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: node server.js