name: release
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout out source code
        uses: actions/checkout@v3
      - run: docker build -t project1/courageabam .
      - name: docker into dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push project1/courageabam  